= Stream-Example: How to use RabbitMQ messaging platform

== Purpose

This multi-repo accompanies workshop session titled *"Stream-Example: How to use RabbitMQ messaging platform"* and includes all code written within the session and potentially more...star+watch this repo for updates!

In the walkthrough, we are using Cloud Foundry spring cloud gateway service and test some filters and predicates on the request headers.

=== Prerequisites

- git installed
- Maven installed and on your path
- Cloud Foundry command line client installed
- RabbitMQ Cloud Foundary MarketPlace Service


=== Step 1 - Download Example Source Code 

    $ cd [GITHUB HOME]
    $ git clone https://github.com/samarsinghal/gateway-sample.git

=== Step 2 - Create RabbitMQ Service Instance

        ```bash
        cf create-service p.rabbitmq single-node rabbitmq
        ```

=== Step 3 - Build

    You can build .jar files like so:

        ```bash
        mvn clean package -f source/pom.xml
        mvn clean package -f processor/pom.xml
        mvn clean package -f sink/pom.xml
        ```

=== Step 4 - Run/Deploy application to Cloud Foundary

    Update deployment manifest to add RabbitMQ service binding:

        ```bash
        cf push
        ```

### Step 5 - Test

    It will take a few minutes to start and then you can view the logs to see the messages get processed:

        ```bash
        curl --location --request GET '<APPLICATION-HOST>/rabbitmq/orderCoffee?coffeeId=123&coffeeName=Cappuccino'
        ```

    You should see output that looks like this:

        ```bash
        cf logs Source
        ```
        OUT Coffee(id=123, name=Cappuccino)

        ```bash
        cf logs Processor
        ```
        Coffee(id=123, name=Cappuccino)
        OUT Bill(id=123, name=Cappuccino, price=5.0)

        ```bash
        cf logs Sink
        ```
        OUT Bill(id=123, name=Cappuccino, price=5.0)

    On RabbitMQ dashboard yo should see below two topic exchange and coffee queue. Monitor messages in the queue.

        Order 
        Billing
